repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '.*\.ipynb'
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

ci:
  autoupdate_schedule: monthly
